# App-level R8 keep rules for the release build.
#
# The Flutter Gradle plugin already supplies Flutter's own rules
# (`packages/flutter_tools/gradle/flutter_proguard_rules.pro`): they `-dontwarn`
# the embedding and keep every `io.flutter.embedding.engine.plugins.FlutterPlugin`
# implementation. This file adds only the gaps those rules leave, and every rule
# states its reason — an unexplained rule is one nobody dares delete.

# --- Flutter plugin registration -------------------------------------------
#
# `GeneratedPluginRegistrant` is generated by `flutter pub get` and loaded *by
# name* from the embedding (it is instantiated reflectively, so R8 sees no static
# reference to keep it). Without this rule a release build starts with zero
# plugins registered: no location, no secure storage, no WebView — and no crash
# that names the cause.
-keep class io.flutter.plugins.GeneratedPluginRegistrant { *; }

# --- Plugin reflection ------------------------------------------------------
#
# `webview_flutter_android` exposes Java to JavaScript through methods annotated
# @JavascriptInterface. Those calls arrive from the page, not from Java, so R8
# cannot see them; a renamed method is simply "not a function" at runtime. Keep
# the annotated members by name.
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# --- Reflective metadata ----------------------------------------------------
#
# The plugins above read annotations, generic signatures and inner-class metadata
# reflectively (MethodChannel argument marshalling, the pigeon-generated host
# APIs in `io.flutter.plugins.webviewflutter` and `…googlemaps`). Stripping these
# attributes turns a working build into a runtime ClassNotFoundException or
# NoSuchMethodError.
-keepattributes *Annotation*, Signature, InnerClasses, EnclosingMethod

# --- App entry point --------------------------------------------------------
#
# Manifest-referenced classes are kept automatically, but MainActivity is the
# app's own entry point; pinning it costs nothing and survives a future refactor
# that stops referencing it directly from the manifest.
-keep class com.hkfastdc.mobile.MainActivity { *; }
