"""enum CHECK constraints — close the gap where 18 columns had none

`SAEnum(X, native_enum=False)` defaults to `create_constraint=False`, so every
autogenerated enum column landed as a bare `VARCHAR` with **no** database-level
guard. Measured on the shipped schema before this revision: of the 20
enum-shaped columns, only 2 were enforced — `driver_licence_submissions.status`
and `driver_documents.kind` — because `a4b8e2f6c150` hand-wrote
`op.create_check_constraint` for them. The other 18 accepted any string that
fit the column width.

Why that matters more than "a missing nicety": the write is silent and the read
is not. `users.role = 'BOGUS'` inserts cleanly, and the *next* load of that row
raises `LookupError` from SQLAlchemy's `_object_value_for_elem` — not
`ValueError`, so no `except ValueError` fallback catches it. A row that is
already written therefore 500s every read it appears in (`/auth/me`, the order
list, …) until someone edits the database by hand. A constraint turns that
into a rejected write at the only moment it is cheap to reject.

This migration only **adds constraints**; it changes no column type and no
width. That is deliberate:

* The column widths in the existing migrations differ from what `create_all`
  derives (it uses the longest enum member) — that drift predates this change
  and is tracked separately by `alembic check`.
* Narrowing a `VARCHAR` on a live table is a rewrite that can fail on existing
  data. Adding a `CHECK` validates the same data but without the type change,
  and the two concerns should not ride in on one revision.

The 18 constraints are added `NOT VALID` **only where a table can already hold
non-conforming rows**; in practice every one of these tables is either new
(`order_disputes`, `dispute_messages`) or has only ever been written through
the ORM's enum binding, which cannot produce an out-of-range value. They are
therefore added *validated* — but the pre-flight check below runs first, so if
that assumption is wrong on a given database the failure names the table and
column instead of dying inside `ALTER TABLE`.

Revision ID: 2e276a320b35
Revises: a1c4e8b7f209
Create Date: 2026-10-02

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2e276a320b35"
down_revision: str | Sequence[str] | None = "a1c4e8b7f209"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# (table, column, constraint name, allowed values). The two constraints that
# already existed are absent on purpose — re-adding them would fail.
_ENUM_CHECKS: tuple[tuple[str, str, str, tuple[str, ...]], ...] = (
    ("users", "role", "ck_users_role", ("PASSENGER", "DRIVER", "ADMIN")),
    (
        "users",
        "gender",
        "ck_users_gender",
        ("MALE", "FEMALE", "OTHER", "UNDISCLOSED"),
    ),
    (
        "users",
        "account_status",
        "ck_users_account_status",
        ("UNVERIFIED", "ACTIVE", "SUSPENDED"),
    ),
    (
        "driver_profiles",
        "status",
        "ck_driver_profiles_status",
        ("PENDING_KYC", "DEPOSIT_REQUIRED", "ACTIVE", "SUSPENDED", "TERMINATED"),
    ),
    (
        "orders",
        "status",
        "ck_orders_status",
        (
            "CREATED",
            "BROADCASTING",
            "ACCEPTED",
            "DRIVER_ARRIVED",
            "IN_TRIP",
            "COMPLETED",
            "CANCELLED",
        ),
    ),
    (
        "ledger_entries",
        "entry_type",
        "ck_ledger_entries_entry_type",
        (
            "DEPOSIT_TOPUP",
            "WEEKLY_FEE_DEDUCTION",
            "PENALTY_DEDUCTION",
            "REFUND",
            "ADJUSTMENT",
        ),
    ),
    (
        "refund_requests",
        "status",
        "ck_refund_requests_status",
        ("PENDING", "APPROVED", "REJECTED"),
    ),
    (
        "fleets",
        "status",
        "ck_fleets_status",
        ("ACTIVE", "SUSPENDED", "DISSOLVED"),
    ),
    (
        "fleet_memberships",
        "member_role",
        "ck_fleet_memberships_member_role",
        ("OWNER", "MANAGER", "MEMBER"),
    ),
    (
        "fleet_memberships",
        "status",
        "ck_fleet_memberships_status",
        ("ACTIVE", "LEFT", "REMOVED"),
    ),
    (
        "order_disputes",
        "raised_by_kind",
        "ck_order_disputes_raised_by_kind",
        ("PASSENGER", "DRIVER", "ADMIN", "SYSTEM", "PLATFORM"),
    ),
    (
        "order_disputes",
        "source",
        "ck_order_disputes_source",
        (
            "AUTO_INTERRUPTED",
            "AUTO_INTERRUPTED_SAFETY",
            "PARTY_REPORT",
            "ADMIN_CREATED",
            "PARTY_CANCELLED_IN_LOCK_WINDOW",
        ),
    ),
    (
        "order_disputes",
        "against_kind",
        "ck_order_disputes_against_kind",
        ("PASSENGER", "DRIVER", "ADMIN", "SYSTEM", "PLATFORM"),
    ),
    (
        "order_disputes",
        "category",
        "ck_order_disputes_category",
        ("FARE", "CONDUCT", "SAFETY", "LOST_ITEM", "APP_ISSUE", "OTHER"),
    ),
    (
        "order_disputes",
        "severity",
        "ck_order_disputes_severity",
        ("LOW", "NORMAL", "HIGH", "SAFETY_CRITICAL"),
    ),
    (
        "order_disputes",
        "status",
        "ck_order_disputes_status",
        ("OPEN", "INVESTIGATING", "AWAITING_PARTY", "RESOLVED", "ESCALATED", "CLOSED"),
    ),
    (
        "order_disputes",
        "resolution",
        "ck_order_disputes_resolution",
        (
            "NONE",
            "CHARGE_PASSENGER",
            "CHARGE_DRIVER",
            "REFUND_PLATFORM_FEE",
            "WAIVED_PLATFORM_FEE",
        ),
    ),
    (
        "dispute_messages",
        "author_kind",
        "ck_dispute_messages_author_kind",
        ("PASSENGER", "DRIVER", "ADMIN", "SYSTEM", "PLATFORM"),
    ),
)


def _check_expression(column: str, values: tuple[str, ...]) -> str:
    """`col IN ('A', 'B')` — the same text SQLAlchemy renders for the column.

    Built here rather than by referencing the model, because a migration must
    be frozen against the schema as it was at this revision: if a member is
    added to the enum later, this file must still mean what it meant today.
    """
    joined = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({joined})"


def _assert_no_offending_rows() -> None:
    """Fail with a named table/column before `ALTER TABLE` fails anonymously.

    `ADD CONSTRAINT` scans the table; on a database that already carries a bad
    value the raw error is `check constraint "..." is violated by some row`,
    which does not say *which* row or even which table when several are added
    in one revision. This turns that into an actionable message, and it is the
    reason the constraints can be added validated rather than `NOT VALID`.
    """
    conn = op.get_bind()
    problems: list[str] = []
    for table, column, name, values in _ENUM_CHECKS:
        allowed = ", ".join(f"'{v}'" for v in values)
        # NULL passes a CHECK, so only non-null out-of-range rows matter.
        count = conn.execute(
            sa.text(
                f"SELECT count(*) FROM {table} "  # noqa: S608 — table/column are literals from the tuple above
                f"WHERE {column} IS NOT NULL AND {column} NOT IN ({allowed})"
            )
        ).scalar_one()
        if count:
            problems.append(f"  {table}.{column}: {count} row(s) outside {name}")
    if problems:
        raise RuntimeError(
            "Refusing to add enum CHECK constraints: existing rows violate them.\n"
            + "\n".join(problems)
            + "\nFix the data (or add the constraint NOT VALID and clean up after) "
            "before re-running this migration."
        )


def upgrade() -> None:
    _assert_no_offending_rows()
    for table, column, name, values in _ENUM_CHECKS:
        op.create_check_constraint(name, table, _check_expression(column, values))


def downgrade() -> None:
    # Reverse order, so the drop sequence mirrors the create sequence.
    for table, _column, name, _values in reversed(_ENUM_CHECKS):
        op.drop_constraint(name, table, type_="check")
