"""core domain: users, drivers, deposits, orders, ledger, otp

Revision ID: 9307e944a592
Revises: 
Create Date: 2026-09-28 18:40:39.335889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9307e944a592'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_expires_at'), 'otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone_e164'), 'otp_codes', ['phone_e164'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.Enum('PASSENGER', 'DRIVER', 'ADMIN', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_e164'), 'users', ['phone_e164'], unique=True)
    op.create_table('driver_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hk_id_last4', sa.String(length=4), nullable=False),
    sa.Column('taxi_driver_plate_no', sa.String(length=10), nullable=False),
    sa.Column('vehicle_reg_mark', sa.String(length=8), nullable=False),
    sa.Column('taxi_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING_KYC', 'DEPOSIT_REQUIRED', 'ACTIVE', 'SUSPENDED', 'TERMINATED', name='driver_status', native_enum=False), nullable=False),
    sa.Column('kyc_reviewed_by', sa.UUID(), nullable=True),
    sa.Column('kyc_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_location_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_driver_profiles_location', 'driver_profiles', ['current_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_driver_profiles_taxi_driver_plate_no'), 'driver_profiles', ['taxi_driver_plate_no'], unique=False)
    op.create_index(op.f('ix_driver_profiles_vehicle_reg_mark'), 'driver_profiles', ['vehicle_reg_mark'], unique=False)
    op.create_table('driver_deposits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_profile_id', sa.UUID(), nullable=False),
    sa.Column('balance_hkd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('held_hkd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('required_hkd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_fulfilled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_profile_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('driver_profile_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('DEPOSIT_TOPUP', 'WEEKLY_FEE_DEDUCTION', 'PENALTY_DEDUCTION', 'REFUND', 'ADJUSTMENT', name='ledger_entry_type', native_enum=False), nullable=False),
    sa.Column('amount_hkd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after_hkd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'created_at', name='uq_ledger_id_created_at')
    )
    op.create_index('ix_ledger_driver_created', 'ledger_entries', ['driver_profile_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_driver_profile_id'), 'ledger_entries', ['driver_profile_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_order_id'), 'ledger_entries', ['order_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'BROADCASTING', 'ACCEPTED', 'DRIVER_ARRIVED', 'IN_TRIP', 'COMPLETED', 'CANCELLED', name='order_status', native_enum=False), nullable=False),
    sa.Column('pickup_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('dropoff_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('dropoff_address', sa.Text(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('taxi_type', sa.String(length=10), nullable=False),
    sa.Column('fare_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tariff_version', sa.String(length=60), nullable=False),
    sa.Column('estimated_total_hkd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('broadcast_radius_km', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_driver_id'), 'orders', ['driver_id'], unique=False)
    op.create_index(op.f('ix_orders_passenger_id'), 'orders', ['passenger_id'], unique=False)
    op.create_index('ix_orders_pickup_geo', 'orders', ['pickup_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_pickup_geo', table_name='orders', postgresql_using='gist')
    op.drop_index(op.f('ix_orders_passenger_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_driver_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_ledger_entries_order_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_driver_profile_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_index('ix_ledger_driver_created', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('driver_deposits')
    op.drop_index(op.f('ix_driver_profiles_vehicle_reg_mark'), table_name='driver_profiles')
    op.drop_index(op.f('ix_driver_profiles_taxi_driver_plate_no'), table_name='driver_profiles')
    op.drop_index('ix_driver_profiles_location', table_name='driver_profiles', postgresql_using='gist')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_users_phone_e164'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_codes_phone_e164'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_expires_at'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
