"""email verification tokens (P-2)

One table. The `users` identity columns it complements already exist in
`e8f4a1c9b720`, so this is purely additive.

Revision ID: f2c7d1a8e940
Revises: e8f4a1c9b720
Create Date: 2026-09-30

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "f2c7d1a8e940"
down_revision: Union[str, Sequence[str], None] = "e8f4a1c9b720"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    # Named explicitly so `downgrade` and a future `drop_index` reference the
    # same name on both sides. An autogenerated name differs between runs.
    op.create_index(
        "uq_email_verification_tokens_token_hash",
        "email_verification_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_email_verification_tokens_user_id", "email_verification_tokens", ["user_id"]
    )
    # Every real query is "the live token for this user" or "anything expired",
    # so the expiry is indexed alongside the owner.
    op.create_index(
        "ix_email_verification_tokens_expires_at", "email_verification_tokens", ["expires_at"]
    )
    op.create_index(
        "ix_email_verification_tokens_created_at", "email_verification_tokens", ["created_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_email_verification_tokens_created_at", table_name="email_verification_tokens")
    op.drop_index("ix_email_verification_tokens_expires_at", table_name="email_verification_tokens")
    op.drop_index("ix_email_verification_tokens_user_id", table_name="email_verification_tokens")
    op.drop_index(
        "uq_email_verification_tokens_token_hash", table_name="email_verification_tokens"
    )
    op.drop_table("email_verification_tokens")
