"""Regenerate the mobile brand assets and Android launcher icons.

The artwork is two 2048x2048 posters (`mobile/branding/source/logo-{zh,en}.jfif`)
that carry the wordmark *in the image* — there is no separate vector mark. So
every size has to be derived, and this is the one place that says how:

  * **In-app** (`assets/branding/logo-{zh,en}.webp`) — 1024px. The splash shows
    the logo at ~240dp, so 1024 is ~4x headroom on the densest phones.
  * **Legacy launcher icon** (`mipmap-*dpi/ic_launcher.png`) — 48/72/96/144/192,
    full bleed.
  * **Adaptive launcher icon** (`drawable-*dpi/ic_launcher_foreground.png`) —
    a 108dp canvas with the poster at 72dp centred, on the poster's own
    background colour.

Why the in-app assets are WebP and the launcher icons are not
-------------------------------------------------------------
The source is a *JPEG*, so it already carries compression noise. Storing that
noise in a PNG preserves it perfectly and expensively — measured on this
artwork:

    px=1024   png-opt 904 KB   png-p256 382 KB   webp-q90  92 KB   jpeg-q90 138 KB

PNG is the worst column, and it is the one we started with. 92 KB is a 10x
saving on art that is flat fills and hard type, which is exactly the content
lossy WebP handles without visible damage. The launcher icons stay PNG because
they are only ~290 KB in total, they are the one thing the OS must decode before
any of our code runs, and a lossy encode at 48px is where artefacts *would*
show.

WebP is safe here because this app ships Android only — there is no `ios/`
directory to worry about, and Android has decoded WebP since API 14.

Why the adaptive icon is built this way
---------------------------------------
An `adaptive-icon` foreground is drawn on a 108dp canvas of which only the
central 66-72dp is guaranteed visible; the launcher masks the rest to a circle,
squircle or rounded square. Dropping the full-bleed poster in would put
"HKFASTDC" and the bottom banner outside that safe zone and they would be cut
off on every modern launcher.

The trick that makes it seamless: the poster's own background is a flat
`#D9DDE6`, so filling the canvas with that same colour and insetting the poster
to 72dp means the mask edge lands on identical colour. The artwork reads as
full-bleed while every element stays inside the safe zone.

Requirements: `pip install Pillow` (not a project dependency — this runs by hand
when the artwork changes, not in CI).

Usage:
    python mobile/tool/gen_branding_assets.py
    python mobile/tool/gen_branding_assets.py --check   # verify, write nothing
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:  # pragma: no cover - operator guidance, not a code path
    print("Pillow is required: pip install Pillow", file=sys.stderr)
    raise SystemExit(2) from None

MOBILE = Path(__file__).resolve().parent.parent
SOURCE = MOBILE / "branding" / "source"
ASSETS = MOBILE / "assets" / "branding"
RES = MOBILE / "android" / "app" / "src" / "main" / "res"

# The poster's own background. Sampled from the artwork's corners; the adaptive
# icon's background layer has to be this exact value or the mask edge shows.
BACKGROUND = "#D9DDE6"

IN_APP_PX = 1024

# Pillow cannot infer a format from a `BytesIO`, so both the write and the
# `--check` round-trip go through this table.
_FORMATS: dict[str, str] = {".png": "PNG", ".webp": "WEBP"}

# Legacy launcher icon sizes, by resource directory.
LEGACY_ICONS: dict[str, int] = {
    "mipmap-mdpi": 48,
    "mipmap-hdpi": 72,
    "mipmap-xhdpi": 96,
    "mipmap-xxhdpi": 144,
    "mipmap-xxxhdpi": 192,
}

# Adaptive icon: 108dp canvas, poster inset to 72dp. See the module docstring.
ADAPTIVE_CANVAS_DP = 108
ADAPTIVE_POSTER_DP = 72
ADAPTIVE_FOREGROUND: dict[str, int] = {
    "drawable-mdpi": 108,
    "drawable-hdpi": 162,
    "drawable-xhdpi": 216,
    "drawable-xxhdpi": 324,
    "drawable-xxxhdpi": 432,
}

# The launcher icon ships the Chinese artwork: the app's default locale is
# `zh-HK` (`lib/app.dart`). Locale-qualified launcher icons are not reliable —
# launchers cache them — so this is one image, chosen once.
ICON_SOURCE = "zh"

ANYDPI_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/tool/gen_branding_assets.py — do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

BACKGROUND_XML = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/tool/gen_branding_assets.py — do not edit by hand. -->
<resources>
    <color name="ic_launcher_background">{BACKGROUND}</color>
</resources>
"""


def _load(name: str) -> Image.Image:
    path = SOURCE / f"{name}.jfif"
    if not path.is_file():
        print(f"missing source artwork: {path}", file=sys.stderr)
        raise SystemExit(2)
    return Image.open(path).convert("RGB")


def _square(image: Image.Image, side: int) -> Image.Image:
    return image.resize((side, side), Image.LANCZOS)


def _foreground(poster: Image.Image, canvas: int) -> Image.Image:
    """The poster centred on a `BACKGROUND`-filled canvas, sized for the safe zone."""
    out = Image.new("RGB", (canvas, canvas), BACKGROUND)
    inset = round(canvas * ADAPTIVE_POSTER_DP / ADAPTIVE_CANVAS_DP)
    out.paste(_square(poster, inset), ((canvas - inset) // 2, (canvas - inset) // 2))
    return out


def _format_for(path: Path) -> str:
    return _FORMATS[path.suffix]


def _save_kwargs(path: Path) -> dict[str, object]:
    if path.suffix == ".webp":
        # q90 / method=6: measured 92 KB at 1024px with no visible damage on
        # flat art. `method` is the encoder effort knob, not a quality knob.
        return {"quality": 90, "method": 6}
    return {"optimize": True}


def _roundtrip(image: Image.Image, path: Path) -> Image.Image:
    """Encode with the settings we would write, then decode — the pixel truth.

    `--check` compares against *this* rather than against `image`, because the
    in-app assets are lossy WebP: a lossy encode never reproduces its input
    exactly, so comparing to the source pixels would report every file stale
    forever, and a check that always fails is a check nobody reads.
    """
    buf = io.BytesIO()
    image.save(buf, format=_format_for(path), **_save_kwargs(path))
    buf.seek(0)
    return Image.open(buf).convert("RGB")


def _plan() -> list[tuple[Path, Image.Image]]:
    """Every file to write, as `(path, image)` — built before anything is saved."""
    zh, en = _load("logo-zh"), _load("logo-en")
    out: list[tuple[Path, Image.Image]] = [
        (ASSETS / "logo-zh.webp", _square(zh, IN_APP_PX)),
        (ASSETS / "logo-en.webp", _square(en, IN_APP_PX)),
    ]

    icon_poster = zh if ICON_SOURCE == "zh" else en
    for directory, px in LEGACY_ICONS.items():
        out.append((RES / directory / "ic_launcher.png", _square(icon_poster, px)))
    for directory, px in ADAPTIVE_FOREGROUND.items():
        out.append((RES / directory / "ic_launcher_foreground.png", _foreground(icon_poster, px)))

    return out


def _text_plan() -> list[tuple[Path, str]]:
    return [
        (RES / "mipmap-anydpi-v26" / "ic_launcher.xml", ANYDPI_XML),
        (RES / "values" / "ic_launcher_background.xml", BACKGROUND_XML),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="report what would change and exit non-zero if anything is stale",
    )
    args = parser.parse_args()

    images = _plan()
    texts = _text_plan()
    stale: list[str] = []

    for path, image in images:
        # Compare decoded pixels rather than file bytes: encoders are free to
        # pick different filters for identical content, which would report every
        # file as stale on a re-run that changed nothing.
        if args.check:
            if not path.is_file():
                stale.append(f"missing  {path.relative_to(MOBILE)}")
                continue
            expected = _roundtrip(image, path)
            existing = Image.open(path).convert("RGB")
            if existing.size != expected.size or existing.tobytes() != expected.tobytes():
                stale.append(f"stale    {path.relative_to(MOBILE)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        image.save(path, format=_format_for(path), **_save_kwargs(path))
        side = f"{image.size[0]}x{image.size[1]}"
        print(f"wrote {path.relative_to(MOBILE)}  ({side}, {path.stat().st_size} B)")

    for path, text in texts:
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(f"stale    {path.relative_to(MOBILE)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(MOBILE)}")

    if args.check:
        if stale:
            print("branding assets are stale:")
            for line in stale:
                print("  " + line)
            return 1
        print("branding assets are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
